<a href="https://colab.research.google.com/github/MarigoldJ/ygl2/blob/main/mycode/nlp/study_20210615.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# import packages

## pip install

In [1]:
! pip install beautifulsoup4 -qU
! pip install newspaper3k -qU
! pip install konlpy -qU

ERROR: konlpy 0.5.2 has requirement beautifulsoup4==4.6.0, but you'll have beautifulsoup4 4.9.3 which is incompatible.


In [77]:
! pip install gensim -qU

     |████████████████████████████████| 23.9MB 1.8MB/s 


In [133]:
! pip install glove_python_binary -qU

     |████████████████████████████████| 952kB 3.9MB/s 


## git clone for Mecab install

In [2]:
! git clone https://github.com/SOMJANG/Mecab-ko-for-Google-Colab.git

fatal: destination path 'Mecab-ko-for-Google-Colab' already exists and is not an empty directory.


In [3]:
! bash Mecab-ko-for-Google-Colab/install_mecab-ko_on_colab190912.sh

Installing konlpy.....
Done
Installing mecab-0.996-ko-0.9.2.tar.gz.....
from https://bitbucket.org/eunjeon/mecab-ko/downloads/mecab-0.996-ko-0.9.2.tar.gz
--2021-06-15 12:07:42--  https://bitbucket.org/eunjeon/mecab-ko/downloads/mecab-0.996-ko-0.9.2.tar.gz
Resolving bitbucket.org (bitbucket.org)... 104.192.141.1, 2406:da00:ff00::22c2:513, 2406:da00:ff00::22c3:9b0a, ...
Connecting to bitbucket.org (bitbucket.org)|104.192.141.1|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://bbuseruploads.s3.amazonaws.com/eunjeon/mecab-ko/downloads/mecab-0.996-ko-0.9.2.tar.gz?Signature=QkPZyMRZ685YYnXpaNFD5mVJrNU%3D&Expires=1623759895&AWSAccessKeyId=AKIA6KOSE3BNJRRFUUX6&versionId=null&response-content-disposition=attachment%3B%20filename%3D%22mecab-0.996-ko-0.9.2.tar.gz%22&response-content-encoding=None [following]
--2021-06-15 12:07:43--  https://bbuseruploads.s3.amazonaws.com/eunjeon/mecab-ko/downloads/mecab-0.996-ko-0.9.2.tar.gz?Signature=QkPZyMRZ685YYnXpaNFD5mVJr

## import

In [194]:
# data edit
import pandas as pd
import numpy as np

# data crawling
from newspaper import Article
from bs4 import BeautifulSoup
import requests

# data tokenization
from konlpy.tag import Mecab

# split data
from sklearn.model_selection import train_test_split

# encoder
from sklearn.feature_extraction.text import CountVectorizer, TfidfTransformer, TfidfVectorizer
from gensim.models import Word2Vec, FastText


# similarity
from sklearn.naive_bayes import MultinomialNB
from sklearn import metrics


# data crawling

In [111]:
class NaverNews():
    '''
    네이버 뉴스 속보 기사 텍스트를 크롤링하는데 사용
    '''

    def __init__(self):
        self.url_list = []
        self.articles = pd.DataFrame(columns=['content', 'category'])

        self.category_list = {100: '정치', 101: '경제', 102: '사회', 103: '생활/문화', 104: '세계', 105: 'IT/과학'}


    def make_url_list(self, code, date, num_pages):
        '''
        네이버 뉴스 속보 기사 url 목록을 반환한다.
        
        네이버 뉴스 속보 > 특정 카테고리 > 페이지 별 기사들의 주소들을 크롤링한다.
        
        code: 어떤 카테고리의 속보 기사들을 불러올지 결정(100, 101, 102, 103, 104, 105)
        date: 어떤 날짜의 속보 기사들을 불러올지 결정
        num_pages: 특정 카테고리의 기사들 중 몇번째 페이지까지 주소를 불러올지 결정
        '''
        url_list = []

        for page in range(num_pages):
            # 속보 기사들이 나열된 url 만들기 (headers가 없으면 권한 없음으로 html파일을 불러올 수 없음)
            url = f'https://news.naver.com/main/list.nhn?mode=LSD&mid=sec&sid1={code}&date={date}&page={page+1}'
            headers = {'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.90 Safari/537.36'}

            # 기사들이 나열된 페이지를 불러오기
            html = requests.get(url, headers=headers)
            html_parse = BeautifulSoup(html.content, 'html.parser')

            # 나열된 기사들의 링크를 url_list에 저장한다.
            news_list = html_parse.select('.newsflash_body > .type06_headline > li > dl')
            for url in news_list:
                url_list.append(url.a.get('href'))  # 한페이지에 대략 10개 기사가 있음

        self.url_list += url_list

        return url_list
    
    def get_articles(self, code, date, num_pages):
        '''
        특정 카테고리, 특정 날짜의 속보 기사들을 지정한 페이지만큼 불러온다.

        code: 어떤 카테고리의 속보 기사들을 불러올지 결정(100, 101, 102, 103, 104, 105)
        date: 어떤 날짜의 속보 기사들을 불러올지 결정
        num_pages: 특정 카테고리의 기사들 중 몇번째 페이지까지 주소를 불러올지 결정
        '''
        # 무슨 기사 내용을 불러올지 출력
        year = date // 10000
        month = (date % 10000) // 100
        day = date % 100

        print(f'{year}년 {month}월 {day}일 <{self.category_list[code]}> 카테고리의 기사를 1~{num_pages} 페이지 내에서 불러옵니다.')

        # 기사 내용을 불러올 기사들의 url list를 만든다.
        print('속보 기사 url 목록을 정리하는 중... ', end='')
        url_list = self.make_url_list(code, date, num_pages)
        print('완료!')

        # 각 기사 url마다 기사 내용을 불러온다.
        print('기사 내용들을 불러오는 중... ', end='')
        text_list = []
        for url in url_list:
            article = Article(url, language='ko')
            article.download()
            article.parse()
            text_list.append(article.text)
        print('완료!')
        print()

        # 모은 기사 내용을 DataFrame으로 정리한다.
        df_articles = pd.DataFrame({'content': text_list, 'category': self.category_list[code], 'code': int(code%10)})
        self.articles = pd.concat([self.articles, df_articles])

        return df_articles
        
    def save_articles(self, name=None):
        '''
        기사 내용을 담은 DataFrame을 저장한다.
        '''
        file_name = f'navernews_{name}.csv'
        self.articles.to_csv(file_name, index=None)

        print('기사 내용을 담은 DataFrame이 저장되었습니다.')

        

In [112]:
naver = NaverNews()
categories = [101, 102, 103, 104, 105]
for cat in categories:
    naver.get_articles(cat, 20210301, 2)

# 저장된 기사 확인
print(naver.articles.shape)
print()
print(naver.articles.isnull().sum())

# 기사 데이터프레임 저장
naver.save_articles(0)

2021년 3월 1일 <경제> 카테고리의 기사를 1~2 페이지 내에서 불러옵니다.
속보 기사 url 목록을 정리하는 중... 완료!
기사 내용들을 불러오는 중... 완료!

2021년 3월 1일 <사회> 카테고리의 기사를 1~2 페이지 내에서 불러옵니다.
속보 기사 url 목록을 정리하는 중... 완료!
기사 내용들을 불러오는 중... 완료!

2021년 3월 1일 <생활/문화> 카테고리의 기사를 1~2 페이지 내에서 불러옵니다.
속보 기사 url 목록을 정리하는 중... 완료!
기사 내용들을 불러오는 중... 완료!

2021년 3월 1일 <세계> 카테고리의 기사를 1~2 페이지 내에서 불러옵니다.
속보 기사 url 목록을 정리하는 중... 완료!
기사 내용들을 불러오는 중... 완료!

2021년 3월 1일 <IT/과학> 카테고리의 기사를 1~2 페이지 내에서 불러옵니다.
속보 기사 url 목록을 정리하는 중... 완료!
기사 내용들을 불러오는 중... 완료!

(100, 3)

content     0
category    0
code        0
dtype: int64
기사 내용을 담은 DataFrame이 저장되었습니다.


# data preprocessing

In [113]:
# 기사 내용을 담은 DataFrame
df = pd.read_csv('navernews_0.csv', index_col=None)
# df = pd.read_csv('https://raw.githubusercontent.com/MarigoldJ/ygl2/main/class/big_crawl.csv', index_col=None)

## Only text or number

* 한글, 영어, 숫자 외의 문자 제거

In [114]:
def only_text_num(df):
    '''
    한글, 영어, 숫자 외의 string을 제거하는 함수
    '''
    df_result = df.copy()

    df_result['content'] = df['content'].str.replace('[^ㄱ-ㅣ가-힣0-9a-zA-Z]', ' ')
    
    return df_result

In [115]:
df = only_text_num(df)
df

content category  code
0   뉴욕 증권거래소의 모습  뉴욕 증권거래소의 모습   미국 뉴욕 증시의 3대 지수가 ...       경제   1.0
1    머니투데이 뉴욕 임동욱 특파원  뉴욕증시가 상승 출발했다 1일 현지시간  오전 9...       경제   1.0
2   가수 김재환이 24일 오후 온라인 생중계로 진행된  제7회 2020 APAN MUS...       경제   1.0
3   한국가스공사 본사 사옥 전경   사진 제공   한국가스공사  한국가스공사 본사 사옥...       경제   1.0
4   금리변수 대외 불확실성  경기회복에 낙관론에  코스피 3300 전망도  코스피가 올...       경제   1.0
..                                                ...      ...   ...
95   디지털데일리 백지영기자  와탭랩스 대표 이동인 는 중소벤처기업부  K 비대면 서비...    IT/과학   5.0
96   이데일리 김국배 기자  국내 소프트웨어 기업 더존비즈온이 미국 사모펀드 운용사인 ...    IT/과학   5.0
97   서울 뉴시스 이해진 왼쪽  네이버 글로벌투자책임자 GIO 와 손정의 오른쪽  일본...    IT/과학   5.0
98  3월1일부로 나흘째 코로나19 백신접종이 진행되고 있는 가운데  일반 국민들을 대상...    IT/과학   5.0
99  세계 최대 음원 스트리밍 업체 스포티파이에서 카카오M이 보유한 음원의 서비스가 1일...    IT/과학   5.0

[100 rows x 3 columns]

## tokenization

* 문장의 토큰화
* 불용어 제거

In [116]:
def tokenize_content(df):
    tokenizer = Mecab()
    stopwords = ['에','는','은','을','했','에게','있','이','의','하','한','다','과','때문','할','수','무단','따른','및','금지','전재','경향신문','기자','는데','가','등','들','파이낸셜','저작','등','뉴스']

    df_result = df.copy()

    # Mecab을 이용한 토큰화
    df_result['token'] = df['content'].apply(lambda x: tokenizer.morphs(x))

    # 불용어 제거
    df_result['token'] = df_result['token'].apply(lambda x: [w for w in x if w not in stopwords])

    # 띄어쓰기로 구분하여 합치기
    df_result['token_line'] = df_result['token'].apply(lambda x: ' '.join(x))

    return df_result


In [117]:
df = tokenize_content(df)
df

content  ...                                         token_line
0   뉴욕 증권거래소의 모습  뉴욕 증권거래소의 모습   미국 뉴욕 증시의 3대 지수가 ...  ...  뉴욕 증권거래소 모습 뉴욕 증권거래소 모습 미국 뉴욕 증시 3 대 지수 일제히 상승...
1    머니투데이 뉴욕 임동욱 특파원  뉴욕증시가 상승 출발했다 1일 현지시간  오전 9...  ...  머니 투데이 뉴욕 임동욱 특파원 뉴욕 증시 상승 출발 1 일 현지 시간 오전 9 시...
2   가수 김재환이 24일 오후 온라인 생중계로 진행된  제7회 2020 APAN MUS...  ...  가수 김재환 24 일 오후 온라인 생중 계 로 진행 된 제 7 회 2020 APAN...
3   한국가스공사 본사 사옥 전경   사진 제공   한국가스공사  한국가스공사 본사 사옥...  ...  한국가스공사 본사 사옥 전경 사진 제공 한국가스공사 한국가스공사 본사 사옥 전경 사...
4   금리변수 대외 불확실성  경기회복에 낙관론에  코스피 3300 전망도  코스피가 올...  ...  금리 변수 대외 불 확실 성 경기 회복 낙관 론 코스피 3300 전망 도 코스피 올...
..                                                ...  ...                                                ...
95   디지털데일리 백지영기자  와탭랩스 대표 이동인 는 중소벤처기업부  K 비대면 서비...  ...  디지털 데일리 백지영 와 탭 랩스 대표 이동인 중소 벤처 기업 부 K 비대 면 서비...
96   이데일리 김국배 기자  국내 소프트웨어 기업 더존비즈온이 미국 사모펀드 운용사인 ...  ...  데일리 김국 배 국내 소프트웨어 기업 더 존비 즈 온이 미국 사모 펀드 운용 사인 ...
97   서울 뉴시스 이해진 왼쪽  네이버 글로벌투자책임자 GIO 와 손정의 오른쪽  일본...  ...  서울 뉴시스 이해진 왼쪽 네이버 글로벌 투자 책임자 GIO 와 손정 오른쪽 일본 소...
98  3월1일부로 나흘째 코로나19 백신접종이 진행되고 있는 가운데  일반 국민들을 대상...  ...  3 월 1 일부 로 나흘 째 코로나 19 백 신접 종이 진행 되 고 가운데 일반 국...
99  세계 최대 음원 스트리밍 업체 스포티파이에서 카카오M이 보유한 음원의 서비스가 1일...  ...  세계 최대 음원 스트리밍 업체 스포티파이 에서 카카오 M 보유 음원 서비스 1 일 ...

[100 rows x 5 columns]

# encoding, embedding

In [118]:
x = df['token_line']
y = df['category']

## dtm

In [125]:
# dtm
encoder_dtm = CountVectorizer()
x_dtm = encoder_dtm.fit_transform(x)

print(x_dtm.shape)
print(x_dtm.toarray())

(100, 4510)
[[1 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 4 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


## TF-IDF

In [127]:
# tfidf 1
encoder_tfidf1 = TfidfTransformer()
x_tfidf1 = encoder_tfidf.fit_transform(x_train_dtm)

# tfidf 2
encoder_tfidf2 = TfidfVectorizer()
x_tfidf2 = encoder_tfidf2.fit_transform(x)

print(x_tfidf1.shape)
print(x_tfidf1.toarray())
print()
print(x_tfidf2.shape)
print(x_tfidf2.toarray())

(100, 4510)
[[0.09688566 0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 ...
 [0.         0.         0.05862327 ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]]

(100, 4510)
[[0.09688566 0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 ...
 [0.         0.         0.05862327 ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]]


## word2vec

* [참고링크 1](https://eda-ai-lab.tistory.com/428)
* 문제점
    * vector의 순서를 정확히 모름(해당 행, 열이 어느 문장, 어느 단어를 임베딩한 것인지 모름)

In [193]:
# word2vec
word2vec = Word2Vec(sentences=df['token'].values, vector_size=100, window=5, min_count=5, workers=4, sg=0)

word_vectors = word2vec.wv
vocabs = word_vectors.key_to_index

print(vocabs)
print()
print(word_vectors[vocabs.keys()].shape)
print(word_vectors[vocabs.keys()])


{'를': 0, '고': 1, '으로': 2, '1': 3, '에서': 4, '로': 5, '도': 6, '3': 7, '일': 8, '와': 9, '습니다': 10, '2': 11, '것': 12, '해': 13, '시': 14, '차량': 15, '인': 16, '년': 17, '기': 18, '적': 19, '지': 20, '만': 21, '명': 22, '된': 23, '되': 24, '눈': 25, '원': 26, '됐': 27, '강원': 28, '며': 29, '까지': 30, '폭설': 31, '월': 32, 'kr': 33, '접종': 34, '성': 35, '5': 36, '면서': 37, '도로': 38, '오후': 39, 'co': 40, '지역': 41, '어': 42, '게': 43, '일본': 44, '면': 45, '한다': 46, '이상': 47, '동해': 48, '2021': 49, '말': 50, '투자': 51, '억': 52, '중': 53, '연합뉴스': 54, '서울': 55, '글로벌': 56, '된다': 57, '위해': 58, '제공': 59, '구간': 60, '더': 61, '부터': 62, '코로나': 63, '19': 64, '자': 65, '전': 66, '10': 67, '분류': 68, '대': 69, '데이터': 70, '기사': 71, '많': 72, '4': 73, '사진': 74, '섹션': 75, '기업': 76, '속초': 77, '통제': 78, '사업': 79, '정체': 80, '개': 81, '겠': 82, '미시령': 83, '고속도로': 84, '홀딩스': 85, '따르': 86, '정보': 87, '발생': 88, '않': 89, '었': 90, 'com': 91, '양양': 92, '시장': 93, '8': 94, '없': 95, '라고': 96, '6': 97, '받': 98, '고립': 99, '온': 100, '돼': 101, '제설': 102, '중심': 103, '네

## glove

* [참고링크 1](https://123okk2.tistory.com/180)
* [참고링크 2](https://wikidocs.net/22885)
* [참고링크 3](https://joyhong.tistory.com/139)

In [134]:
from glove import Corpus, Glove

In [185]:
# glove
corpus = Corpus()
corpus.fit(df['token'].to_numpy(), window=5)

glove = Glove(no_components=100, learning_rate=0.05)
glove.fit(corpus.matrix, epochs=20, no_threads=4, verbose=True)
glove.add_dictionary(corpus.dictionary)

Performing 20 training epochs with 4 threads
Epoch 0
Epoch 1
Epoch 2
Epoch 3
Epoch 4
Epoch 5
Epoch 6
Epoch 7
Epoch 8
Epoch 9
Epoch 10
Epoch 11
Epoch 12
Epoch 13
Epoch 14
Epoch 15
Epoch 16
Epoch 17
Epoch 18
Epoch 19


In [189]:
print(len(corpus.dictionary))
print(corpus.dictionary)

4953
{'뉴욕': 0, '증권거래소': 1, '모습': 2, '미국': 3, '증시': 4, '3': 5, '대': 6, '지수': 7, '일제히': 8, '상승': 9, '출발': 10, '1': 11, '일': 12, '오전': 13, '9': 14, '시': 15, '40': 16, '분': 17, '현지': 18, '시각': 19, '현재': 20, 'NYSE': 21, '에서': 22, '다우존스': 23, '30': 24, '산업': 25, '평균': 26, '전': 27, '거래일': 28, '보다': 29, '58': 30, '오른': 31, '만': 32, '1420': 33, '21': 34, '기록': 35, '고': 36, '스탠더드': 37, '앤드': 38, '푸': 39, '어스': 40, 'S': 41, 'P': 42, '500': 43, '도': 44, '3865': 45, '53': 46, '으로': 47, '대비': 48, '43': 49, '상승세': 50, '를': 51, '보이': 52, '기술': 53, '주': 54, '중심': 55, '나스닥': 56, '38': 57, '3375': 58, '00': 59, '오르내리': 60, '조': 61, '9000': 62, '억': 63, '달러': 64, '2100': 65, '원': 66, '규모': 67, '추가': 68, '경기': 69, '부양책': 70, '대한': 71, '기대': 72, '투자': 73, '심리': 74, '긍정': 75, '적': 76, '인': 77, '영향': 78, '미쳤': 79, '다는': 80, '분석': 81, '나온다': 82, '부': 83, '양안': 84, '지난달': 85, '27': 86, '미': 87, '하원': 88, '통과': 89, '이번': 90, '상원': 91, '여부': 92, '주목': 93, '된다': 94, '바이든': 95, '대통령': 96, '신속': 97, '촉구': 98, '며': 9

In [192]:
print(glove.word_vectors.shape)
print(glove.word_vectors)

(4953, 100)
[[-0.00487038  0.01021201 -0.01070731 ...  0.00453893  0.00727796
  -0.00321674]
 [ 0.00088332 -0.00084154 -0.00150622 ... -0.00084007 -0.00172036
   0.00340155]
 [ 0.00812345  0.01333622 -0.00786382 ...  0.00907154  0.00093848
  -0.0005574 ]
 ...
 [ 0.0003597  -0.0003903  -0.00204149 ... -0.00485639  0.00101701
  -0.00227626]
 [ 0.00531629  0.0023121  -0.0027449  ...  0.0059314   0.00298573
  -0.00352483]
 [-0.0007423   0.00410722  0.00233747 ...  0.0067534   0.00082637
  -0.0002086 ]]


## fasttext

* [참고링크](https://omicro03.medium.com/%EC%9E%90%EC%97%B0%EC%96%B4%EC%B2%98%EB%A6%AC-nlp-15%EC%9D%BC%EC%B0%A8-fasttext-2b1aca6b3b56)
* 코드 구조는 word2vec과 비슷함. 같은 패키지에 있어서 그런듯.

In [195]:
# fasttext
model_ft = FastText(df['token'], vector_size=100, window=5, min_count=5, workers=4, sg=1)

In [198]:
print(model_ft.wv.vectors.shape)
print(model_ft.wv.vectors)

(1314, 100)
[[-0.25053257  0.02420785 -0.04481788 ... -0.08299613 -0.12820143
   0.01746627]
 [-0.19300656  0.13228339 -0.06095158 ... -0.21133035 -0.14039317
   0.10419968]
 [-0.3062771   0.12860647 -0.0136441  ... -0.16838416 -0.10070912
   0.14708643]
 ...
 [-0.2707727   0.10412049 -0.09622911 ... -0.08269995 -0.20382926
   0.11085606]
 [-0.28378457  0.12501319 -0.121588   ... -0.08205237 -0.2083441
   0.08930241]
 [-0.34723476  0.15623282 -0.13998388 ... -0.12236807 -0.24669085
   0.13143712]]


In [201]:
print(model_ft.wv.key_to_index)
print(model_ft.wv.key_to_index.keys())
print(model_ft.wv.index_to_key)

{'를': 0, '고': 1, '으로': 2, '1': 3, '에서': 4, '로': 5, '도': 6, '3': 7, '일': 8, '와': 9, '습니다': 10, '2': 11, '것': 12, '해': 13, '시': 14, '차량': 15, '인': 16, '년': 17, '기': 18, '적': 19, '지': 20, '만': 21, '명': 22, '된': 23, '되': 24, '눈': 25, '원': 26, '됐': 27, '강원': 28, '며': 29, '까지': 30, '폭설': 31, '월': 32, 'kr': 33, '접종': 34, '성': 35, '5': 36, '면서': 37, '도로': 38, '오후': 39, 'co': 40, '지역': 41, '어': 42, '게': 43, '일본': 44, '면': 45, '한다': 46, '이상': 47, '동해': 48, '2021': 49, '말': 50, '투자': 51, '억': 52, '중': 53, '연합뉴스': 54, '서울': 55, '글로벌': 56, '된다': 57, '위해': 58, '제공': 59, '구간': 60, '더': 61, '부터': 62, '코로나': 63, '19': 64, '자': 65, '전': 66, '10': 67, '분류': 68, '대': 69, '데이터': 70, '기사': 71, '많': 72, '4': 73, '사진': 74, '섹션': 75, '기업': 76, '속초': 77, '통제': 78, '사업': 79, '정체': 80, '개': 81, '겠': 82, '미시령': 83, '고속도로': 84, '홀딩스': 85, '따르': 86, '정보': 87, '발생': 88, '않': 89, '었': 90, 'com': 91, '양양': 92, '시장': 93, '8': 94, '없': 95, '라고': 96, '6': 97, '받': 98, '고립': 99, '온': 100, '돼': 101, '제설': 102, '중심': 103, '네

# modeling

In [ ]:
test_size = 0.3
rnum = 33

## Naive Bayes Classifier

* [참고링크 1](https://wikidocs.net/22892)

In [99]:
x_train, x_test, y_train, y_test = train_test_split(x_tfidf1, y_tfidf1, test_size=0.3 ,random_state=33)
print(f'Length of train dataset : {len(x_train)}')
print(f'Length of test dataset : {len(x_test)}')

Length of train dataset : 70
Length of test dataset : 30


## Logistic Regression

* [참고링크 1](http://hleecaster.com/ml-logistic-regression-example/)

In [202]:
from sklearn.linear_model import LogisticRegression
model_lr = LogisticRegression()

In [207]:
x_train, x_test, y_train, y_test = train_test_split(x_tfidf1.toarray(), y, test_size=0.3 ,random_state=33)
print(f'Length of train dataset : {len(x_train)}')
print(f'Length of test dataset : {len(x_test)}')

Length of train dataset : 70
Length of test dataset : 30


In [208]:
model_lr.fit(x_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [210]:
# y_pred = model_lr.predict(x_test)
print(model_lr.score(x_test, y_test))

0.5333333333333333


## Decision Tree classifier

* [참고링크 1](https://injo.tistory.com/15)

In [211]:
from sklearn.tree import DecisionTreeClassifier

model_dtclf = DecisionTreeClassifier()

In [212]:
x_train, x_test, y_train, y_test = train_test_split(x_tfidf1.toarray(), y, test_size=0.3 ,random_state=33)
print(f'Length of train dataset : {len(x_train)}')
print(f'Length of test dataset : {len(x_test)}')

Length of train dataset : 70
Length of test dataset : 30


In [213]:
model_dtclf.fit(x_train, y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [215]:
# y_pred = model_dtclf.predict(x_test)
print(model_dtclf.score(x_test, y_test))

0.43333333333333335


## random forest Classifier

* [참고링크 1](https://todayisbetterthanyesterday.tistory.com/51)

In [221]:
from sklearn.ensemble import RandomForestClassifier

model_rfclf = RandomForestClassifier()

In [222]:
x_train, x_test, y_train, y_test = train_test_split(x_tfidf1.toarray(), y, test_size=0.3 ,random_state=33)
print(f'Length of train dataset : {len(x_train)}')
print(f'Length of test dataset : {len(x_test)}')

Length of train dataset : 70
Length of test dataset : 30


In [223]:
model_rfclf.fit(x_train, y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [224]:
# y_pred = model_rfclf.predict(x_test)
print(model_rfclf.score(x_test, y_test))

0.5666666666666667


## gradient Boosting Classifier

* [참고링크 1](https://woolulu.tistory.com/30)

In [216]:
from sklearn.ensemble import GradientBoostingClassifier

model_gbclf = GradientBoostingClassifier()

In [217]:
x_train, x_test, y_train, y_test = train_test_split(x_tfidf1.toarray(), y, test_size=0.3 ,random_state=33)
print(f'Length of train dataset : {len(x_train)}')
print(f'Length of test dataset : {len(x_test)}')

Length of train dataset : 70
Length of test dataset : 30


In [218]:
model_gbclf.fit(x_train, y_train)

GradientBoostingClassifier(ccp_alpha=0.0, criterion='friedman_mse', init=None,
                           learning_rate=0.1, loss='deviance', max_depth=3,
                           max_features=None, max_leaf_nodes=None,
                           min_impurity_decrease=0.0, min_impurity_split=None,
                           min_samples_leaf=1, min_samples_split=2,
                           min_weight_fraction_leaf=0.0, n_estimators=100,
                           n_iter_no_change=None, presort='deprecated',
                           random_state=None, subsample=1.0, tol=0.0001,
                           validation_fraction=0.1, verbose=0,
                           warm_start=False)

In [219]:
# y_pred = model_gbclf.predict(x_test)
print(model_gbclf.score(x_test, y_test))

0.6


# check similarity